#!/usr/bin/python

import psutil
import argparse
import pprint

pp = pprint.PrettyPrinter(indent=4)

parser = argparse.ArgumentParser(description='Monitor partitions.  Alert on low disk space.')
args = parser.parse_args()

partits = psutil.disk_partitions()
pp.pprint(partits)
